### PR TITLE
implemented grafanna and prometheus for monitoring

### PR DESCRIPTION
**Pull request by uchiha-vivek**
**http://localhost:5000/metrics** This will show up the metrics for Node js application.

**http://localhost:9090** Prometheus Localport 

**http://localhost:3000/?orgId=1** Graffana localhost [Here you can view Graffana dashboard]

### CODE REVIEW

**Comment by uchiha-vivek** [comment]
@vaibhavyadav-dev Sir please review

**Comment by vaibhavyadav-dev** [comment]
@uchiha-vivek share your screenshot of prometheus-grafana

**Comment by vaibhavyadav-dev** [comment]
> @uchiha-vivek share your screenshot of prometheus-grafana

@uchiha-vivek in working condition with dashboards

**Comment by uchiha-vivek** [comment]
@vaibhavyadav-dev  ok sir

**Comment by uchiha-vivek** [comment]
Screenshot (113)
Screenshot (114)

**Review by vaibhavyadav-dev — CHANGES_REQUESTED** [review]
- Where is grafana dashboard, provide me it's json 
- When newer version is available why you've used older versions ?
- why you've used nodejs-applications, it's good you've used for testing but you've to remove it after testing.
- Prometheus is throwing error in my dashboard
Screenshot 2024-10-19 224420


- one thing, I don't understand you're exposing :5000/metrics and listening to :9090/metrics.
- Did you copy pasted it ?
### After successful implementation you've to provide dashboard like this
image

image

**Comment by uchiha-vivek** [comment]
@vaibhavyadav-dev  ok, I first implemented it for my local project and it was working fine. I will try to fix it.

**Comment by vaibhavyadav-dev** [comment]
> @vaibhavyadav-dev ok, I first implemented it for my local project and it was working fine. I will try to fix it.

@uchiha-vivek it's ok to look other codebases for learning and exploring, but you should know how and why it works like that, remember bro, you're doing for learning purpose and that will help you in long run not to increase your PR count.

**Comment by uchiha-vivek** [comment]
@vaibhavyadav-dev  Sir i am fixing each issue step by step as mentioned by you . Its gonna be good learning session

**Comment by vaibhavyadav-dev** [comment]
@uchiha-vivek are working on this issue ?

**Pull request closed without merging**
